#############################################
#	Synopsys Design Constraints (SDC)
#	For FPGA fabric 
#	Description: Disable configurable memory outputs for PnR
#	Author: Xifan TANG 
#	Organization: University of Utah 
#############################################

set_disable_timing fpga_top/grid_io_bottom_bottom_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/sofa_plus_io_sofa_plus_ccff_mem/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/grid_io_bottom_bottom_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/sofa_plus_io_sofa_plus_ccff_mem/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/grid_io_bottom_bottom_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/sofa_plus_io_sofa_plus_ccff_mem/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/grid_io_right_right_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/sofa_plus_io_sofa_plus_ccff_mem/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/grid_io_right_right_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/sofa_plus_io_sofa_plus_ccff_mem/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/grid_io_right_right_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/sofa_plus_io_sofa_plus_ccff_mem/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/grid_io_top_top_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/sofa_plus_io_sofa_plus_ccff_mem/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/grid_io_top_top_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/sofa_plus_io_sofa_plus_ccff_mem/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/grid_io_top_top_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/sofa_plus_io_sofa_plus_ccff_mem/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/grid_io_left_left_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/sofa_plus_io_sofa_plus_ccff_mem/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/grid_io_left_left_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/sofa_plus_io_sofa_plus_ccff_mem/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/grid_io_left_left_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/sofa_plus_io_sofa_plus_ccff_mem/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut*_arith_*/frac_lut*_arith_sofa_plus_ccff_mem/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut*_arith_*/frac_lut*_arith_sofa_plus_ccff_mem/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut*_arith_*/frac_lut*_arith_sofa_plus_ccff_mem/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff_*/sofa_plus_dff_sofa_plus_ccff_mem/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff_*/sofa_plus_dff_sofa_plus_ccff_mem/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff_*/sofa_plus_dff_sofa_plus_ccff_mem/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/mem_fabric_out_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/mem_fabric_out_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/mem_fabric_out_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/mem_fle_*_in_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/mem_fle_*_in_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/mem_fle_*_in_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cby_*__*_/mem_left_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_left_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cby_*__*_/mem_left_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cby_*__*_/mem_left_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_left_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cby_*__*_/mem_left_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cby_*__*_/mem_left_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_left_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cby_*__*_/mem_left_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/sofa_plus_ccff_*_/CFGQ
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/CFGQN
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/sofa_plus_ccff_*_/CFGQ
